export interface EmojiItem {
  readonly emoji: string;
  readonly name: string;
  readonly keywords?: readonly string[];
}

export interface EmojiCategory {
  readonly id: string;
  readonly name: string;
  readonly icon: string;
  readonly emojis: readonly EmojiItem[];
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      { emoji: '😀', name: 'Grinning face', keywords: ['smile', 'happy'] },
      { emoji: '😃', name: 'Grinning face with big eyes', keywords: ['smile', 'happy', 'joy'] },
      { emoji: '😄', name: 'Grinning face with smiling eyes', keywords: ['smile', 'happy', 'laugh'] },
      { emoji: '😁', name: 'Beaming face with smiling eyes', keywords: ['smile', 'grin'] },
      { emoji: '😆', name: 'Grinning squinting face', keywords: ['laugh', 'happy'] },
      { emoji: '😅', name: 'Grinning face with sweat', keywords: ['relief', 'sweat'] },
      { emoji: '😂', name: 'Face with tears of joy', keywords: ['laugh', 'cry', 'tears'] },
      { emoji: '🤣', name: 'Rolling on the floor laughing', keywords: ['rofl', 'lol', 'laugh'] },
      { emoji: '🥲', name: 'Smiling face with tear', keywords: ['proud', 'touched'] },
      { emoji: '🥹', name: 'Face holding back tears', keywords: ['emotional', 'gratitude'] },
      { emoji: '☺️', name: 'Smiling face', keywords: ['blush', 'warm'] },
      { emoji: '😊', name: 'Smiling face with smiling eyes', keywords: ['happy', 'blush'] },
      { emoji: '😇', name: 'Smiling face with halo', keywords: ['angel', 'innocent'] },
      { emoji: '🙂', name: 'Slightly smiling face', keywords: ['smile'] },
      { emoji: '🙃', name: 'Upside-down face', keywords: ['silly', 'sarcasm'] },
      { emoji: '😉', name: 'Winking face', keywords: ['wink', 'flirt'] },
      { emoji: '😌', name: 'Relieved face', keywords: ['peace', 'calm'] },
      { emoji: '😍', name: 'Smiling face with heart-eyes', keywords: ['love', 'crush'] },
      { emoji: '🥰', name: 'Care (smiling face with hearts)', keywords: ['care', 'love', 'affection'] },
      { emoji: '😘', name: 'Face blowing a kiss', keywords: ['kiss', 'love'] },
      { emoji: '😗', name: 'Kissing face', keywords: ['kiss'] },
      { emoji: '😙', name: 'Kissing face with smiling eyes', keywords: ['kiss'] },
      { emoji: '😚', name: 'Kissing face with closed eyes', keywords: ['kiss'] },
      { emoji: '😋', name: 'Face savoring food', keywords: ['yum', 'delicious'] },
      { emoji: '😛', name: 'Face with tongue', keywords: ['tongue', 'silly'] },
      { emoji: '😝', name: 'Squinting face with tongue', keywords: ['playful'] },
      { emoji: '😜', name: 'Winking face with tongue', keywords: ['joke', 'party'] },
      { emoji: '🤪', name: 'Zany face', keywords: ['crazy', 'wild'] },
      { emoji: '🤨', name: 'Face with raised eyebrow', keywords: ['skeptical'] },
      { emoji: '🧐', name: 'Face with monocle', keywords: ['curious', 'inspect'] },
      { emoji: '🤓', name: 'Nerd face', keywords: ['geek', 'smart'] },
      { emoji: '😎', name: 'Smiling face with sunglasses', keywords: ['cool', 'chill'] },
      { emoji: '🥸', name: 'Disguised face', keywords: ['disguise', 'mustache'] },
      { emoji: '🤩', name: 'Star-struck', keywords: ['excited', 'star'] },
      { emoji: '🥳', name: 'Partying face', keywords: ['party', 'celebrate', 'horn'] },
      { emoji: '😏', name: 'Smirking face', keywords: ['smirk', 'flirt'] },
      { emoji: '😒', name: 'Unamused face', keywords: ['annoyed'] },
      { emoji: '😞', name: 'Disappointed face', keywords: ['sad'] },
      { emoji: '😔', name: 'Pensive face', keywords: ['regret', 'sad'] },
      { emoji: '😟', name: 'Worried face', keywords: ['worry'] },
      { emoji: '😕', name: 'Confused face', keywords: ['confused'] },
      { emoji: '🙁', name: 'Slightly frowning face', keywords: ['frown'] },
      { emoji: '☹️', name: 'Frowning face', keywords: ['sad', 'unhappy'] },
      { emoji: '😣', name: 'Persevering face', keywords: ['struggle'] },
      { emoji: '😖', name: 'Confounded face', keywords: ['frustrated'] },
      { emoji: '😫', name: 'Tired face', keywords: ['exhausted'] },
      { emoji: '😩', name: 'Weary face', keywords: ['tired'] },
      { emoji: '🥺', name: 'Pleading face', keywords: ['puppy eyes', 'please'] },
      { emoji: '😢', name: 'Crying face', keywords: ['tear', 'sad'] },
      { emoji: '😭', name: 'Loudly crying face', keywords: ['bawling', 'sobbing'] },
      { emoji: '😮‍💨', name: 'Face exhaling', keywords: ['sigh', 'relief'] },
      { emoji: '😤', name: 'Face with steam from nose', keywords: ['huff', 'determined'] },
      { emoji: '😠', name: 'Angry face', keywords: ['mad', 'grumpy'] },
      { emoji: '😡', name: 'Enraged face', keywords: ['pouting', 'furious'] },
      { emoji: '🤬', name: 'Face with symbols on mouth', keywords: ['swearing', 'rage'] },
      { emoji: '🤯', name: 'Exploding head', keywords: ['mind blown', 'shock'] },
      { emoji: '😳', name: 'Flushed face', keywords: ['blush', 'embarrassed'] },
      { emoji: '🥵', name: 'Hot face', keywords: ['sweating', 'heat'] },
      { emoji: '🥶', name: 'Cold face', keywords: ['freezing', 'chill'] },
      { emoji: '😱', name: 'Face screaming in fear', keywords: ['scared', 'shock'] },
      { emoji: '😨', name: 'Fearful face', keywords: ['scared'] },
      { emoji: '😰', name: 'Anxious face with sweat', keywords: ['nervous'] },
      { emoji: '😥', name: 'Sad but relieved face', keywords: ['close call'] },
      { emoji: '😓', name: 'Downcast face with sweat', keywords: ['stress'] },
      { emoji: '🤗', name: 'Hugging face', keywords: ['hug', 'warmth', 'care'] },
      { emoji: '🤔', name: 'Thinking face', keywords: ['think', 'ponder'] },
      { emoji: '🫣', name: 'Face with peeking eye', keywords: ['shy', 'scared'] },
      { emoji: '🤭', name: 'Face with hand over mouth', keywords: ['giggle', 'oops'] },
      { emoji: '🫢', name: 'Face with open eyes and hand over mouth', keywords: ['gasp', 'shock'] },
      { emoji: '🫡', name: 'Saluting face', keywords: ['respect', 'salute'] },
      { emoji: '🤫', name: 'Shushing face', keywords: ['quiet', 'secret'] },
      { emoji: '🫠', name: 'Melting face', keywords: ['dissolving', 'hot'] },
      { emoji: '🤥', name: 'Lying face', keywords: ['pinocchio'] },
      { emoji: '😶', name: 'Face without mouth', keywords: ['speechless'] },
      { emoji: '😐', name: 'Neutral face', keywords: ['meh'] },
      { emoji: '😑', name: 'Expressionless face', keywords: ['blank'] },
      { emoji: '😬', name: 'Grimacing face', keywords: ['awkward', 'cringe'] },
      { emoji: '🫨', name: 'Shaking face', keywords: ['earthquake', 'vibrate'] },
      { emoji: '🙄', name: 'Face with rolling eyes', keywords: ['eye roll'] },
      { emoji: '😯', name: 'Hushed face', keywords: ['surprise'] },
      { emoji: '😦', name: 'Frowning face with open mouth', keywords: ['aww'] },
      { emoji: '😧', name: 'Anguished face', keywords: ['worried'] },
      { emoji: '😮', name: 'Face with open mouth', keywords: ['surprised', 'wow'] },
      { emoji: '😲', name: 'Astonished face', keywords: ['shocked'] },
      { emoji: '🥱', name: 'Yawning face', keywords: ['sleepy', 'bored'] },
      { emoji: '😴', name: 'Sleeping face', keywords: ['zzz'] },
      { emoji: '🤤', name: 'Drooling face', keywords: ['hungry'] },
      { emoji: '😪', name: 'Sleepy face', keywords: ['tired'] },
      { emoji: '😵', name: 'Face with crossed-out eyes', keywords: ['dizzy'] },
      { emoji: '😵‍💫', name: 'Face with spiral eyes', keywords: ['hypnotized'] },
      { emoji: '🤐', name: 'Zipper-mouth face', keywords: ['sealed'] },
      { emoji: '🥴', name: 'Woozy face', keywords: ['drunk', 'dazed'] },
      { emoji: '🤢', name: 'Nauseated face', keywords: ['gross', 'sick'] },
      { emoji: '🤮', name: 'Face vomiting', keywords: ['puke', 'sick'] },
      { emoji: '🤧', name: 'Sneezing face', keywords: ['sneeze', 'cold'] },
      { emoji: '😷', name: 'Face with medical mask', keywords: ['mask', 'ill'] },
      { emoji: '🤒', name: 'Face with thermometer', keywords: ['fever', 'sick'] },
      { emoji: '🤕', name: 'Face with head-bandage', keywords: ['hurt', 'injury'] },
      { emoji: '🤑', name: 'Money-mouth face', keywords: ['rich', 'dollar'] },
      { emoji: '🤠', name: 'Cowboy hat face', keywords: ['western'] },
      { emoji: '😈', name: 'Smiling face with horns', keywords: ['devil', 'mischief'] },
      { emoji: '👿', name: 'Angry face with horns', keywords: ['demon'] },
      { emoji: '🤡', name: 'Clown face', keywords: ['circus'] },
      { emoji: '💩', name: 'Pile of poo', keywords: ['poop', 'crap'] },
      { emoji: '👻', name: 'Ghost', keywords: ['spooky', 'halloween'] },
      { emoji: '💀', name: 'Skull', keywords: ['dead', 'skeleton'] },
      { emoji: '☠️', name: 'Skull and crossbones', keywords: ['danger', 'pirate'] },
      { emoji: '👽', name: 'Alien', keywords: ['ufo'] },
      { emoji: '👾', name: 'Alien monster', keywords: ['arcade', 'game'] },
      { emoji: '🤖', name: 'Robot', keywords: ['bot'] },
      { emoji: '🎃', name: 'Jack-o-lantern', keywords: ['pumpkin', 'halloween'] },
    ],
  },
  {
    id: 'gestures',
    name: 'People & Body',
    icon: '👋',
    emojis: [
      { emoji: '👋', name: 'Waving hand', keywords: ['wave', 'hello', 'bye'] },
      { emoji: '🤚', name: 'Raised back of hand', keywords: ['hand'] },
      { emoji: '🖐️', name: 'Hand with fingers splayed', keywords: ['five'] },
      { emoji: '✋', name: 'Raised hand', keywords: ['stop', 'high five'] },
      { emoji: '🖖', name: 'Vulcan salute', keywords: ['spock', 'star trek'] },
      { emoji: '👌', name: 'OK hand', keywords: ['perfect', 'good'] },
      { emoji: '🤌', name: 'Pinched fingers', keywords: ['italian'] },
      { emoji: '🤏', name: 'Pinching hand', keywords: ['small', 'little'] },
      { emoji: '✌️', name: 'Victory hand', keywords: ['peace', 'two'] },
      { emoji: '🤞', name: 'Crossed fingers', keywords: ['luck', 'hope'] },
      { emoji: '🫰', name: 'Hand with index finger and thumb crossed', keywords: ['love', 'money'] },
      { emoji: '🤟', name: 'Love-you gesture', keywords: ['ily'] },
      { emoji: '🤘', name: 'Sign of the horns', keywords: ['rock', 'metal'] },
      { emoji: '🤙', name: 'Call me hand', keywords: ['shaka', 'phone'] },
      { emoji: '👈', name: 'Backhand index pointing left', keywords: ['left'] },
      { emoji: '👉', name: 'Backhand index pointing right', keywords: ['right'] },
      { emoji: '👆', name: 'Backhand index pointing up', keywords: ['up'] },
      { emoji: '🖕', name: 'Middle finger', keywords: ['rude'] },
      { emoji: '👇', name: 'Backhand index pointing down', keywords: ['down'] },
      { emoji: '☝️', name: 'Index pointing up', keywords: ['one'] },
      { emoji: '🫵', name: 'Index pointing at the viewer', keywords: ['you'] },
      { emoji: '👍', name: 'Thumbs up', keywords: ['like', 'yes', 'approve'] },
      { emoji: '👎', name: 'Thumbs down', keywords: ['dislike', 'no'] },
      { emoji: '✊', name: 'Raised fist', keywords: ['power'] },
      { emoji: '👊', name: 'Oncoming fist', keywords: ['punch', 'fist bump'] },
      { emoji: '🤛', name: 'Left-facing fist', keywords: ['fist bump'] },
      { emoji: '🤜', name: 'Right-facing fist', keywords: ['fist bump'] },
      { emoji: '👏', name: 'Clapping hands', keywords: ['applause', 'praise'] },
      { emoji: '🙌', name: 'Raising hands', keywords: ['cheer', 'celebrate'] },
      { emoji: '🫶', name: 'Heart hands', keywords: ['love'] },
      { emoji: '👐', name: 'Open hands', keywords: ['hug'] },
      { emoji: '🤲', name: 'Palms up together', keywords: ['prayer'] },
      { emoji: '🤝', name: 'Handshake', keywords: ['deal', 'agreement'] },
      { emoji: '🙏', name: 'Folded hands', keywords: ['pray', 'thank you', 'please'] },
      { emoji: '✍️', name: 'Writing hand', keywords: ['write'] },
      { emoji: '💅', name: 'Nail polish', keywords: ['sassy'] },
      { emoji: '🤳', name: 'Selfie', keywords: ['camera', 'photo'] },
      { emoji: '💪', name: 'Flexed biceps', keywords: ['strong', 'muscle'] },
      { emoji: '🦾', name: 'Mechanical arm', keywords: ['cyborg', 'prosthetic'] },
      { emoji: '🦿', name: 'Mechanical leg', keywords: ['cyborg'] },
      { emoji: '🦵', name: 'Leg', keywords: ['limb'] },
      { emoji: '🦶', name: 'Foot', keywords: ['feet'] },
      { emoji: '👂', name: 'Ear', keywords: ['listen', 'hear'] },
      { emoji: '👃', name: 'Nose', keywords: ['smell'] },
      { emoji: '🧠', name: 'Brain', keywords: ['smart', 'mind'] },
      { emoji: '🫀', name: 'Anatomical heart', keywords: ['organ'] },
      { emoji: '🫁', name: 'Lungs', keywords: ['breathe'] },
      { emoji: '🦷', name: 'Tooth', keywords: ['dentist'] },
      { emoji: '🦴', name: 'Bone', keywords: ['skeleton'] },
      { emoji: '👀', name: 'Eyes', keywords: ['look', 'see', 'peek'] },
      { emoji: '👁️', name: 'Eye', keywords: ['look'] },
      { emoji: '👅', name: 'Tongue', keywords: ['taste'] },
      { emoji: '👄', name: 'Mouth', keywords: ['lips'] },
      { emoji: '🫦', name: 'Biting lip', keywords: ['nervous', 'flirt'] },
      { emoji: '🫂', name: 'People hugging', keywords: ['hug', 'care', 'support'] },
    ],
  },
  {
    id: 'hearts',
    name: 'Hearts & Symbols',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', name: 'Red heart', keywords: ['love', 'heart'] },
      { emoji: '🧡', name: 'Orange heart', keywords: ['love', 'orange'] },
      { emoji: '💛', name: 'Yellow heart', keywords: ['love', 'yellow'] },
      { emoji: '💚', name: 'Green heart', keywords: ['love', 'green'] },
      { emoji: '💙', name: 'Blue heart', keywords: ['love', 'blue'] },
      { emoji: '💜', name: 'Purple heart', keywords: ['love', 'purple'] },
      { emoji: '🖤', name: 'Black heart', keywords: ['love', 'black'] },
      { emoji: '🤍', name: 'White heart', keywords: ['love', 'white'] },
      { emoji: '🤎', name: 'Brown heart', keywords: ['love', 'brown'] },
      { emoji: '🩷', name: 'Pink heart', keywords: ['love', 'pink'] },
      { emoji: '🩵', name: 'Light blue heart', keywords: ['love', 'cyan'] },
      { emoji: '🩶', name: 'Grey heart', keywords: ['love', 'gray'] },
      { emoji: '💔', name: 'Broken heart', keywords: ['heartbreak', 'sad'] },
      { emoji: '❤️‍🔥', name: 'Heart on fire', keywords: ['passion'] },
      { emoji: '❤️‍🩹', name: 'Mending heart', keywords: ['healing'] },
      { emoji: '❣️', name: 'Heart exclamation', keywords: ['love'] },
      { emoji: '💕', name: 'Two hearts', keywords: ['love'] },
      { emoji: '💞', name: 'Revolving hearts', keywords: ['love'] },
      { emoji: '💓', name: 'Beating heart', keywords: ['heartbeat'] },
      { emoji: '💗', name: 'Growing heart', keywords: ['love'] },
      { emoji: '💖', name: 'Sparkling heart', keywords: ['sparkle'] },
      { emoji: '💘', name: 'Heart with arrow', keywords: ['cupid'] },
      { emoji: '💝', name: 'Heart with ribbon', keywords: ['gift'] },
      { emoji: '💟', name: 'Heart decoration', keywords: ['heart'] },
      { emoji: '💯', name: 'Hundred points', keywords: ['100', 'perfect'] },
      { emoji: '🔥', name: 'Fire', keywords: ['hot', 'lit'] },
      { emoji: '✨', name: 'Sparkles', keywords: ['magic', 'shine'] },
      { emoji: '⭐', name: 'Star', keywords: ['star'] },
      { emoji: '🌟', name: 'Glowing star', keywords: ['shine'] },
      { emoji: '💫', name: 'Dizzy', keywords: ['sparkle'] },
      { emoji: '💥', name: 'Collision', keywords: ['boom', 'bang'] },
      { emoji: '⚡', name: 'High voltage', keywords: ['lightning', 'zap'] },
      { emoji: '🌈', name: 'Rainbow', keywords: ['pride'] },
      { emoji: '☀️', name: 'Sun', keywords: ['sunny'] },
      { emoji: '🌙', name: 'Crescent moon', keywords: ['night'] },
      { emoji: '🎉', name: 'Celebrate (party popper)', keywords: ['party', 'congrats', 'celebrate'] },
      { emoji: '🎊', name: 'Confetti ball', keywords: ['celebrate', 'party'] },
      { emoji: '🎈', name: 'Balloon', keywords: ['party', 'birthday'] },
      { emoji: '🎁', name: 'Wrapped gift', keywords: ['present', 'birthday'] },
      { emoji: '🎂', name: 'Birthday cake', keywords: ['cake', 'celebrate'] },
      { emoji: '🏆', name: 'Trophy', keywords: ['winner', 'first place'] },
      { emoji: '🥇', name: '1st place medal', keywords: ['gold', 'winner'] },
      { emoji: '🥈', name: '2nd place medal', keywords: ['silver'] },
      { emoji: '🥉', name: '3rd place medal', keywords: ['bronze'] },
      { emoji: '✅', name: 'Check mark button', keywords: ['yes', 'done'] },
      { emoji: '❌', name: 'Cross mark', keywords: ['no', 'wrong'] },
      { emoji: '⚠️', name: 'Warning', keywords: ['alert', 'danger'] },
      { emoji: '🚀', name: 'Rocket', keywords: ['launch', 'blast'] },
      { emoji: '☕', name: 'Hot beverage', keywords: ['coffee', 'tea'] },
      { emoji: '🍕', name: 'Pizza', keywords: ['food'] },
      { emoji: '🍻', name: 'Clinking beer mugs', keywords: ['cheers', 'beer'] },
      { emoji: '🥂', name: 'Clinking glasses', keywords: ['cheers', 'celebrate', 'toast'] },
    ],
  },
  {
    id: 'animals',
    name: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      { emoji: '🐶', name: 'Dog face', keywords: ['puppy', 'pet'] },
      { emoji: '🐱', name: 'Cat face', keywords: ['kitten', 'pet'] },
      { emoji: '🐭', name: 'Mouse face', keywords: ['mouse'] },
      { emoji: '🐹', name: 'Hamster', keywords: ['pet'] },
      { emoji: '🐰', name: 'Rabbit face', keywords: ['bunny'] },
      { emoji: '🦊', name: 'Fox', keywords: ['clever'] },
      { emoji: '🐻', name: 'Bear', keywords: ['teddy'] },
      { emoji: '🐼', name: 'Panda', keywords: ['bear'] },
      { emoji: '🐨', name: 'Koala', keywords: ['australia'] },
      { emoji: '🐯', name: 'Tiger face', keywords: ['cat'] },
      { emoji: '🦁', name: 'Lion', keywords: ['king'] },
      { emoji: '🐮', name: 'Cow face', keywords: ['moo'] },
      { emoji: '🐷', name: 'Pig face', keywords: ['oink'] },
      { emoji: '🐸', name: 'Frog', keywords: ['ribbit'] },
      { emoji: '🐵', name: 'Monkey face', keywords: ['banana'] },
      { emoji: '🐔', name: 'Chicken', keywords: ['cluck'] },
      { emoji: '🐧', name: 'Penguin', keywords: ['antarctica'] },
      { emoji: '🐦', name: 'Bird', keywords: ['tweet'] },
      { emoji: '🦆', name: 'Duck', keywords: ['quack'] },
      { emoji: '🦅', name: 'Eagle', keywords: ['bird'] },
      { emoji: '🦉', name: 'Owl', keywords: ['wise'] },
      { emoji: '🦇', name: 'Bat', keywords: ['vampire'] },
      { emoji: '🐺', name: 'Wolf', keywords: ['howl'] },
      { emoji: '🐗', name: 'Boar', keywords: ['wild'] },
      { emoji: '🐴', name: 'Horse face', keywords: ['pony'] },
      { emoji: '🦄', name: 'Unicorn', keywords: ['magic', 'fantasy'] },
      { emoji: '🐝', name: 'Honeybee', keywords: ['buzz'] },
      { emoji: '🐛', name: 'Bug', keywords: ['insect'] },
      { emoji: '🦋', name: 'Butterfly', keywords: ['pretty'] },
      { emoji: '🐌', name: 'Snail', keywords: ['slow'] },
      { emoji: '🐞', name: 'Lady beetle', keywords: ['ladybug'] },
      { emoji: '🐢', name: 'Turtle', keywords: ['slow'] },
      { emoji: '🐍', name: 'Snake', keywords: ['slither'] },
      { emoji: '🐙', name: 'Octopus', keywords: ['sea'] },
      { emoji: '🦀', name: 'Crab', keywords: ['ocean'] },
      { emoji: '🐟', name: 'Fish', keywords: ['sea'] },
      { emoji: '🐬', name: 'Dolphin', keywords: ['ocean'] },
      { emoji: '🐳', name: 'Spouting whale', keywords: ['whale'] },
      { emoji: '🌸', name: 'Cherry blossom', keywords: ['flower', 'spring'] },
      { emoji: '🌹', name: 'Rose', keywords: ['flower', 'love'] },
      { emoji: '🌻', name: 'Sunflower', keywords: ['flower', 'summer'] },
      { emoji: '🌼', name: 'Blossom', keywords: ['flower'] },
      { emoji: '🌷', name: 'Tulip', keywords: ['flower'] },
      { emoji: '🌱', name: 'Seedling', keywords: ['plant', 'growth'] },
      { emoji: '🌲', name: 'Evergreen tree', keywords: ['pine', 'christmas'] },
      { emoji: '🌳', name: 'Deciduous tree', keywords: ['nature'] },
      { emoji: '🌴', name: 'Palm tree', keywords: ['beach', 'tropical'] },
      { emoji: '🌵', name: 'Cactus', keywords: ['desert'] },
      { emoji: '🍀', name: 'Four leaf clover', keywords: ['lucky', 'irish'] },
      { emoji: '🍁', name: 'Maple leaf', keywords: ['autumn', 'fall'] },
      { emoji: '🍂', name: 'Fallen leaf', keywords: ['autumn'] },
      { emoji: '🍃', name: 'Leaf fluttering in wind', keywords: ['breeze'] },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: '🍕',
    emojis: [
      { emoji: '🍏', name: 'Green apple', keywords: ['fruit'] },
      { emoji: '🍎', name: 'Red apple', keywords: ['fruit'] },
      { emoji: '🍐', name: 'Pear', keywords: ['fruit'] },
      { emoji: '🍊', name: 'Tangerine', keywords: ['orange', 'fruit'] },
      { emoji: '🍋', name: 'Lemon', keywords: ['sour', 'citrus'] },
      { emoji: '🍌', name: 'Banana', keywords: ['fruit'] },
      { emoji: '🍉', name: 'Watermelon', keywords: ['summer', 'fruit'] },
      { emoji: '🍇', name: 'Grapes', keywords: ['fruit', 'wine'] },
      { emoji: '🍓', name: 'Strawberry', keywords: ['berry', 'fruit'] },
      { emoji: '🫐', name: 'Blueberries', keywords: ['berry'] },
      { emoji: '🍒', name: 'Cherries', keywords: ['fruit'] },
      { emoji: '🍑', name: 'Peach', keywords: ['fruit'] },
      { emoji: '🍍', name: 'Pineapple', keywords: ['tropical'] },
      { emoji: '🥥', name: 'Coconut', keywords: ['tropical'] },
      { emoji: '🥑', name: 'Avocado', keywords: ['guacamole'] },
      { emoji: '🍔', name: 'Hamburger', keywords: ['burger', 'fast food'] },
      { emoji: '🍟', name: 'French fries', keywords: ['fast food'] },
      { emoji: '🍕', name: 'Pizza', keywords: ['slice'] },
      { emoji: '🌭', name: 'Hot dog', keywords: ['sausage'] },
      { emoji: '🥪', name: 'Sandwich', keywords: ['lunch'] },
      { emoji: '🌮', name: 'Taco', keywords: ['mexican'] },
      { emoji: '🌯', name: 'Burrito', keywords: ['wrap'] },
      { emoji: '🍣', name: 'Sushi', keywords: ['japanese'] },
      { emoji: '🍜', name: 'Steaming bowl', keywords: ['ramen', 'noodles'] },
      { emoji: '🍝', name: 'Spaghetti', keywords: ['pasta', 'italian'] },
      { emoji: '🍦', name: 'Soft ice cream', keywords: ['dessert'] },
      { emoji: '🍩', name: 'Doughnut', keywords: ['dessert', 'sweet'] },
      { emoji: '🍪', name: 'Cookie', keywords: ['chocolate chip'] },
      { emoji: '🍫', name: 'Chocolate bar', keywords: ['sweet'] },
      { emoji: '🍿', name: 'Popcorn', keywords: ['movie', 'snack'] },
      { emoji: '☕', name: 'Hot beverage', keywords: ['coffee', 'tea'] },
      { emoji: '🧋', name: 'Bubble tea', keywords: ['boba'] },
      { emoji: '🍷', name: 'Wine glass', keywords: ['alcohol'] },
      { emoji: '🍸', name: 'Cocktail glass', keywords: ['martini'] },
      { emoji: '🍹', name: 'Tropical drink', keywords: ['cocktail'] },
      { emoji: '🍺', name: 'Beer mug', keywords: ['beer', 'pub'] },
      { emoji: '🍻', name: 'Clinking beer mugs', keywords: ['cheers', 'beer'] },
      { emoji: '🥂', name: 'Clinking glasses', keywords: ['champagne', 'toast'] },
    ],
  },
];

export function searchEmojis(query: string): readonly EmojiItem[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return EMOJI_CATEGORIES.flatMap((c) => c.emojis);
  }
  const results: EmojiItem[] = [];
  for (const cat of EMOJI_CATEGORIES) {
    for (const item of cat.emojis) {
      if (
        item.name.toLowerCase().includes(q) ||
        item.emoji === q ||
        item.keywords?.some((k) => k.toLowerCase().includes(q))
      ) {
        results.push(item);
      }
    }
  }
  return results;
}
